services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: always
    environment:
      - CLUSTER_NAME=hadoop-cluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HDFS_CONF_dfs_replication=1
    ports:
      - "9870:9870" # UI do NameNode
      - "9000:9000" # Porta HDFS
    volumes:
      - namenode_data:/hadoop/dfs/name
    networks:
      - hadoop
    env_file:
      - ./hadoop.env

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    restart: always
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    ports:
      - "9864:9864" # UI do DataNode
    volumes:
      - datanode_data:/hadoop/dfs/data
    networks:
      - hadoop
    env_file:
      - ./hadoop.env

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    container_name: resourcemanager
    restart: always
    environment:
      - YARN_CONF_yarn_resourcemanager_hostname=resourcemanager
      - YARN_CONF_yarn_nodemanager_aux_services=mapreduce_shuffle
      - SERVICE_PRECONDITION=namenode:9000,namenode:9870,datanode:9864
    ports:
      - "8088:8088" # UI do ResourceManager
    networks:
      - hadoop
    env_file:
      - ./hadoop.env

  nodemanager:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    container_name: nodemanager
    restart: always
    environment:
      - YARN_CONF_yarn_resourcemanager_hostname=resourcemanager
      - YARN_CONF_yarn_nodemanager_aux_services=mapreduce_shuffle
      - SERVICE_PRECONDITION=namenode:9000,namenode:9870,datanode:9864,resourcemanager:8088
    networks:
      - hadoop
    env_file:
      - ./hadoop.env

  historyserver:
    image: bde2020/hadoop-historyserver:2.0.0-hadoop3.2.1-java8
    container_name: historyserver
    restart: always
    environment:
      - YARN_CONF_yarn_resourcemanager_hostname=resourcemanager
      - SERVICE_PRECONDITION=namenode:9000,namenode:9870,datanode:9864,resourcemanager:8088
    ports:
      - "8188:8188" # Timeline Server
      - "19888:19888" # Job History Server
    networks:
      - hadoop
    env_file:
      - ./hadoop.env

  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
      POSTGRES_DB: metastore
    ports:
      - "5432:5432" # Porta do banco de dados
    networks:
      - hadoop
    volumes:
      - postgres_data:/var/lib/postgresql/data

  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-metastore
    environment:
      - HIVE_METASTORE_USER=hive
      - HIVE_METASTORE_PASSWORD=hive
      - HIVE_METASTORE_DB=metastore
      - HIVE_METASTORE_HOST=hive-metastore
      - HIVE_CONF_hive_metastore_uris=thrift://hive-metastore:9083
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HADOOP_HEAPSIZE=512
      - JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
      - CORE_CONF_hadoop_proxyuser_hive_hosts=*

    networks:
      - hadoop
    depends_on:
      - namenode
      - datanode
      - resourcemanager
      - postgres
    ports:
      - "9083:9083"
    volumes:
      - ./hive-site.xml:/opt/hive/conf/hive-site.xml

  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-server
    environment:
      - HIVE_METASTORE_URI=thrift://hive-metastore:9083
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HADOOP_HEAPSIZE=1024
      - JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
    networks:
      - hadoop
    depends_on:
      - hive-metastore
      - namenode
    ports:
      - "10000:10000"
    volumes:
      - ./hive-site.xml:/opt/hive/conf/hive-site.xml

volumes:
  namenode_data:
  datanode_data:
  postgres_data:

networks:
  hadoop:
